title: EC6XX
description: This website hosts all study material for EC 6th sem @JSSSTU
author: Mohamed Farhan Fazal
theme: jekyll-theme-cayman
github:
  youtube_url: https://www.youtube.com/c/MohamedFazal